#############################################################################
# Makefile for building: MiniPy
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  MiniPy.pro
# Template: app
# Command: /opt/qt5.7.0/bin/qmake -o Makefile MiniPy.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv7-a -O2 -march=armv7-a -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../opencv/opencv-3.2.0/output/include -I../../../opencv/opencv-3.2.0/output/include/opencv -I../../../opencv/opencv-3.2.0/output/include/opencv2 -I/opt/qt5.7.0/include -I/opt/qt5.7.0/include/QtWidgets -I/opt/qt5.7.0/include/QtGui -I/opt/qt5.7.0/include/QtCore -I. -I. -I/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /opt/qt5.7.0/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MiniPy1.0.0
DISTDIR = /home/jiangyu/code/qt/MiniPy/.tmp/MiniPy1.0.0
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /home/jiangyu/opencv/opencv-3.2.0/output/lib/libopencv_highgui.so /home/jiangyu/opencv/opencv-3.2.0/output/lib/libopencv_core.so /home/jiangyu/opencv/opencv-3.2.0/output/lib/libopencv_imgproc.so /home/jiangyu/opencv/opencv-3.2.0/output/lib/libopencv_imgcodecs.so /home/jiangyu/opencv/opencv-3.2.0/output/lib/libopencv_videoio.so -L/opt/qt5.7.0/lib -lQt5Widgets -L/opt/tslib1.4/lib -lQt5Gui -lQt5Core -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-none-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		v4l2Cap.c \
		workerthread.cpp \
		opencv_measure.cpp \
		makeexif.c moc_widget.cpp \
		moc_workerthread.cpp
OBJECTS       = main.o \
		widget.o \
		v4l2Cap.o \
		workerthread.o \
		opencv_measure.o \
		makeexif.o \
		moc_widget.o \
		moc_workerthread.o
DIST          = /opt/qt5.7.0/mkspecs/features/spec_pre.prf \
		/opt/qt5.7.0/mkspecs/common/unix.conf \
		/opt/qt5.7.0/mkspecs/common/linux.conf \
		/opt/qt5.7.0/mkspecs/common/sanitize.conf \
		/opt/qt5.7.0/mkspecs/common/gcc-base.conf \
		/opt/qt5.7.0/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5.7.0/mkspecs/common/g++-base.conf \
		/opt/qt5.7.0/mkspecs/common/g++-unix.conf \
		/opt/qt5.7.0/mkspecs/qconfig.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5.7.0/mkspecs/features/qt_functions.prf \
		/opt/qt5.7.0/mkspecs/features/qt_config.prf \
		/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/qt5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5.7.0/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.7.0/mkspecs/features/default_pre.prf \
		/opt/qt5.7.0/mkspecs/features/resolve_config.prf \
		/opt/qt5.7.0/mkspecs/features/default_post.prf \
		/opt/qt5.7.0/mkspecs/features/warn_on.prf \
		/opt/qt5.7.0/mkspecs/features/qt.prf \
		/opt/qt5.7.0/mkspecs/features/resources.prf \
		/opt/qt5.7.0/mkspecs/features/moc.prf \
		/opt/qt5.7.0/mkspecs/features/uic.prf \
		/opt/qt5.7.0/mkspecs/features/unix/thread.prf \
		/opt/qt5.7.0/mkspecs/features/file_copies.prf \
		/opt/qt5.7.0/mkspecs/features/testcase_targets.prf \
		/opt/qt5.7.0/mkspecs/features/exceptions.prf \
		/opt/qt5.7.0/mkspecs/features/yacc.prf \
		/opt/qt5.7.0/mkspecs/features/lex.prf \
		MiniPy.pro widget.h \
		v4l2Cap.h \
		workerthread.h \
		opencv_measure.h \
		exifparam.h main.cpp \
		widget.cpp \
		v4l2Cap.c \
		workerthread.cpp \
		opencv_measure.cpp \
		makeexif.c
QMAKE_TARGET  = MiniPy
DESTDIR       = 
TARGET        = MiniPy


first: all
####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MiniPy.pro /opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf /opt/qt5.7.0/mkspecs/features/spec_pre.prf \
		/opt/qt5.7.0/mkspecs/common/unix.conf \
		/opt/qt5.7.0/mkspecs/common/linux.conf \
		/opt/qt5.7.0/mkspecs/common/sanitize.conf \
		/opt/qt5.7.0/mkspecs/common/gcc-base.conf \
		/opt/qt5.7.0/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5.7.0/mkspecs/common/g++-base.conf \
		/opt/qt5.7.0/mkspecs/common/g++-unix.conf \
		/opt/qt5.7.0/mkspecs/qconfig.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.7.0/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5.7.0/mkspecs/features/qt_functions.prf \
		/opt/qt5.7.0/mkspecs/features/qt_config.prf \
		/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/opt/qt5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5.7.0/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.7.0/mkspecs/features/default_pre.prf \
		/opt/qt5.7.0/mkspecs/features/resolve_config.prf \
		/opt/qt5.7.0/mkspecs/features/default_post.prf \
		/opt/qt5.7.0/mkspecs/features/warn_on.prf \
		/opt/qt5.7.0/mkspecs/features/qt.prf \
		/opt/qt5.7.0/mkspecs/features/resources.prf \
		/opt/qt5.7.0/mkspecs/features/moc.prf \
		/opt/qt5.7.0/mkspecs/features/uic.prf \
		/opt/qt5.7.0/mkspecs/features/unix/thread.prf \
		/opt/qt5.7.0/mkspecs/features/file_copies.prf \
		/opt/qt5.7.0/mkspecs/features/testcase_targets.prf \
		/opt/qt5.7.0/mkspecs/features/exceptions.prf \
		/opt/qt5.7.0/mkspecs/features/yacc.prf \
		/opt/qt5.7.0/mkspecs/features/lex.prf \
		MiniPy.pro \
		/opt/qt5.7.0/lib/libQt5Widgets.prl \
		/opt/qt5.7.0/lib/libQt5Gui.prl \
		/opt/qt5.7.0/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MiniPy.pro
/opt/qt5.7.0/mkspecs/features/spec_pre.prf:
/opt/qt5.7.0/mkspecs/common/unix.conf:
/opt/qt5.7.0/mkspecs/common/linux.conf:
/opt/qt5.7.0/mkspecs/common/sanitize.conf:
/opt/qt5.7.0/mkspecs/common/gcc-base.conf:
/opt/qt5.7.0/mkspecs/common/gcc-base-unix.conf:
/opt/qt5.7.0/mkspecs/common/g++-base.conf:
/opt/qt5.7.0/mkspecs/common/g++-unix.conf:
/opt/qt5.7.0/mkspecs/qconfig.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_core.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_help.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_network.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_script.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5.7.0/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qt5.7.0/mkspecs/features/qt_functions.prf:
/opt/qt5.7.0/mkspecs/features/qt_config.prf:
/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
/opt/qt5.7.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5.7.0/mkspecs/features/exclusive_builds.prf:
/opt/qt5.7.0/mkspecs/features/default_pre.prf:
/opt/qt5.7.0/mkspecs/features/resolve_config.prf:
/opt/qt5.7.0/mkspecs/features/default_post.prf:
/opt/qt5.7.0/mkspecs/features/warn_on.prf:
/opt/qt5.7.0/mkspecs/features/qt.prf:
/opt/qt5.7.0/mkspecs/features/resources.prf:
/opt/qt5.7.0/mkspecs/features/moc.prf:
/opt/qt5.7.0/mkspecs/features/uic.prf:
/opt/qt5.7.0/mkspecs/features/unix/thread.prf:
/opt/qt5.7.0/mkspecs/features/file_copies.prf:
/opt/qt5.7.0/mkspecs/features/testcase_targets.prf:
/opt/qt5.7.0/mkspecs/features/exceptions.prf:
/opt/qt5.7.0/mkspecs/features/yacc.prf:
/opt/qt5.7.0/mkspecs/features/lex.prf:
MiniPy.pro:
/opt/qt5.7.0/lib/libQt5Widgets.prl:
/opt/qt5.7.0/lib/libQt5Gui.prl:
/opt/qt5.7.0/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MiniPy.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents widget.h v4l2Cap.h workerthread.h opencv_measure.h exifparam.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp v4l2Cap.c workerthread.cpp opencv_measure.cpp makeexif.c $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_widget.cpp moc_workerthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_workerthread.cpp
moc_widget.cpp: /opt/qt5.7.0/include/QtWidgets/QWidget \
		/opt/qt5.7.0/include/QtWidgets/qwidget.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs.h \
		/opt/qt5.7.0/include/QtCore/qglobal.h \
		/opt/qt5.7.0/include/QtCore/qconfig.h \
		/opt/qt5.7.0/include/QtCore/qfeatures.h \
		/opt/qt5.7.0/include/QtCore/qsystemdetection.h \
		/opt/qt5.7.0/include/QtCore/qprocessordetection.h \
		/opt/qt5.7.0/include/QtCore/qcompilerdetection.h \
		/opt/qt5.7.0/include/QtCore/qtypeinfo.h \
		/opt/qt5.7.0/include/QtCore/qtypetraits.h \
		/opt/qt5.7.0/include/QtCore/qisenum.h \
		/opt/qt5.7.0/include/QtCore/qsysinfo.h \
		/opt/qt5.7.0/include/QtCore/qlogging.h \
		/opt/qt5.7.0/include/QtCore/qflags.h \
		/opt/qt5.7.0/include/QtCore/qatomic.h \
		/opt/qt5.7.0/include/QtCore/qbasicatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.7.0/include/QtCore/qgenericatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.7.0/include/QtCore/qatomic_msvc.h \
		/opt/qt5.7.0/include/QtCore/qglobalstatic.h \
		/opt/qt5.7.0/include/QtCore/qmutex.h \
		/opt/qt5.7.0/include/QtCore/qnumeric.h \
		/opt/qt5.7.0/include/QtCore/qversiontagging.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs.h \
		/opt/qt5.7.0/include/QtCore/qnamespace.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.7.0/include/QtCore/qobject.h \
		/opt/qt5.7.0/include/QtCore/qstring.h \
		/opt/qt5.7.0/include/QtCore/qchar.h \
		/opt/qt5.7.0/include/QtCore/qbytearray.h \
		/opt/qt5.7.0/include/QtCore/qrefcount.h \
		/opt/qt5.7.0/include/QtCore/qarraydata.h \
		/opt/qt5.7.0/include/QtCore/qstringbuilder.h \
		/opt/qt5.7.0/include/QtCore/qlist.h \
		/opt/qt5.7.0/include/QtCore/qalgorithms.h \
		/opt/qt5.7.0/include/QtCore/qiterator.h \
		/opt/qt5.7.0/include/QtCore/qhashfunctions.h \
		/opt/qt5.7.0/include/QtCore/qpair.h \
		/opt/qt5.7.0/include/QtCore/qbytearraylist.h \
		/opt/qt5.7.0/include/QtCore/qstringlist.h \
		/opt/qt5.7.0/include/QtCore/qregexp.h \
		/opt/qt5.7.0/include/QtCore/qstringmatcher.h \
		/opt/qt5.7.0/include/QtCore/qcoreevent.h \
		/opt/qt5.7.0/include/QtCore/qscopedpointer.h \
		/opt/qt5.7.0/include/QtCore/qmetatype.h \
		/opt/qt5.7.0/include/QtCore/qvarlengtharray.h \
		/opt/qt5.7.0/include/QtCore/qcontainerfwd.h \
		/opt/qt5.7.0/include/QtCore/qobject_impl.h \
		/opt/qt5.7.0/include/QtCore/qmargins.h \
		/opt/qt5.7.0/include/QtGui/qpaintdevice.h \
		/opt/qt5.7.0/include/QtCore/qrect.h \
		/opt/qt5.7.0/include/QtCore/qsize.h \
		/opt/qt5.7.0/include/QtCore/qpoint.h \
		/opt/qt5.7.0/include/QtGui/qpalette.h \
		/opt/qt5.7.0/include/QtGui/qcolor.h \
		/opt/qt5.7.0/include/QtGui/qrgb.h \
		/opt/qt5.7.0/include/QtGui/qrgba64.h \
		/opt/qt5.7.0/include/QtGui/qbrush.h \
		/opt/qt5.7.0/include/QtCore/qvector.h \
		/opt/qt5.7.0/include/QtGui/qmatrix.h \
		/opt/qt5.7.0/include/QtGui/qpolygon.h \
		/opt/qt5.7.0/include/QtGui/qregion.h \
		/opt/qt5.7.0/include/QtCore/qdatastream.h \
		/opt/qt5.7.0/include/QtCore/qiodevice.h \
		/opt/qt5.7.0/include/QtCore/qline.h \
		/opt/qt5.7.0/include/QtGui/qtransform.h \
		/opt/qt5.7.0/include/QtGui/qpainterpath.h \
		/opt/qt5.7.0/include/QtGui/qimage.h \
		/opt/qt5.7.0/include/QtGui/qpixelformat.h \
		/opt/qt5.7.0/include/QtGui/qpixmap.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer.h \
		/opt/qt5.7.0/include/QtCore/qshareddata.h \
		/opt/qt5.7.0/include/QtCore/qhash.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.7.0/include/QtGui/qfont.h \
		/opt/qt5.7.0/include/QtGui/qfontmetrics.h \
		/opt/qt5.7.0/include/QtGui/qfontinfo.h \
		/opt/qt5.7.0/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.7.0/include/QtGui/qcursor.h \
		/opt/qt5.7.0/include/QtGui/qkeysequence.h \
		/opt/qt5.7.0/include/QtGui/qevent.h \
		/opt/qt5.7.0/include/QtCore/qvariant.h \
		/opt/qt5.7.0/include/QtCore/qmap.h \
		/opt/qt5.7.0/include/QtCore/qdebug.h \
		/opt/qt5.7.0/include/QtCore/qtextstream.h \
		/opt/qt5.7.0/include/QtCore/qlocale.h \
		/opt/qt5.7.0/include/QtCore/qset.h \
		/opt/qt5.7.0/include/QtCore/qcontiguouscache.h \
		/opt/qt5.7.0/include/QtCore/qurl.h \
		/opt/qt5.7.0/include/QtCore/qurlquery.h \
		/opt/qt5.7.0/include/QtCore/qfile.h \
		/opt/qt5.7.0/include/QtCore/qfiledevice.h \
		/opt/qt5.7.0/include/QtGui/qvector2d.h \
		/opt/qt5.7.0/include/QtGui/qtouchdevice.h \
		/opt/qt5.7.0/include/QtWidgets/QMessageBox \
		/opt/qt5.7.0/include/QtWidgets/qmessagebox.h \
		/opt/qt5.7.0/include/QtWidgets/qdialog.h \
		/opt/qt5.7.0/include/QtGui/QImage \
		/opt/qt5.7.0/include/QtGui/QPixmap \
		/opt/qt5.7.0/include/QtCore/QTimer \
		/opt/qt5.7.0/include/QtCore/qtimer.h \
		/opt/qt5.7.0/include/QtCore/qbasictimer.h \
		/opt/qt5.7.0/include/QtCore/QTime \
		/opt/qt5.7.0/include/QtCore/qdatetime.h \
		/opt/qt5.7.0/include/QtCore/QDebug \
		/opt/qt5.7.0/include/QtGui/QPainter \
		/opt/qt5.7.0/include/QtGui/qpainter.h \
		/opt/qt5.7.0/include/QtGui/qtextoption.h \
		/opt/qt5.7.0/include/QtGui/qpen.h \
		/opt/qt5.7.0/include/QtCore/QThread \
		/opt/qt5.7.0/include/QtCore/qthread.h \
		/opt/qt5.7.0/include/QtGui/QCloseEvent \
		/opt/qt5.7.0/include/QtCore/QMutex \
		/opt/qt5.7.0/include/QtCore/QMutexLocker \
		v4l2Cap.h \
		workerthread.h \
		/opt/qt5.7.0/include/QtCore/QObject \
		/opt/qt5.7.0/include/QtCore/QSemaphore \
		/opt/qt5.7.0/include/QtCore/qsemaphore.h \
		opencv_measure.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv_modules.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvdef.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/hal/interface.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/version.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ptr.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/neon_utils.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/traits.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/matx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/saturate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/fast_math.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/bufferpool.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/persistence.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/operations.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/utility.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/core_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/optim.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ovx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/features2d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/miniflann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/defines.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/config.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/affine.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d/calib3d_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/flann_base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/general.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/matrix.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/params.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/any.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/saving.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/nn_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/result_set.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/all_indices.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dynamic_bitset.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dist.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/heap.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/allocator.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/random.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_single_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kmeans_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/logger.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/composite_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/linear_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_table.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/autotuned_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/ground_truth.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/index_testing.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/timer.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/sampling.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui/highgui_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/imgproc_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio/videoio_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/ml.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/objdetect_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo/photo_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/emdL1.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_transformer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/hist_cost.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_distance.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda_types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/matchers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/camera.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/blenders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/background_segm.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/stabilizer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/global_motion.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/outlier_rejection.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/frame_source.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/log.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/inpainting.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/deblurring.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/wobble_suppression.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/ring_buffer.hpp \
		widget.h \
		/opt/qt5.7.0/bin/moc
	/opt/qt5.7.0/bin/moc $(DEFINES) -I/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++ -I/home/jiangyu/code/qt/MiniPy -I/home/jiangyu/opencv/opencv-3.2.0/output/include -I/home/jiangyu/opencv/opencv-3.2.0/output/include/opencv -I/home/jiangyu/opencv/opencv-3.2.0/output/include/opencv2 -I/opt/qt5.7.0/include -I/opt/qt5.7.0/include/QtWidgets -I/opt/qt5.7.0/include/QtGui -I/opt/qt5.7.0/include/QtCore -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3 -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/arm-none-linux-gnueabi -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/backward -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include-fixed -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/libc/usr/include widget.h -o moc_widget.cpp

moc_workerthread.cpp: /opt/qt5.7.0/include/QtCore/QObject \
		/opt/qt5.7.0/include/QtCore/qobject.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs.h \
		/opt/qt5.7.0/include/QtCore/qnamespace.h \
		/opt/qt5.7.0/include/QtCore/qglobal.h \
		/opt/qt5.7.0/include/QtCore/qconfig.h \
		/opt/qt5.7.0/include/QtCore/qfeatures.h \
		/opt/qt5.7.0/include/QtCore/qsystemdetection.h \
		/opt/qt5.7.0/include/QtCore/qprocessordetection.h \
		/opt/qt5.7.0/include/QtCore/qcompilerdetection.h \
		/opt/qt5.7.0/include/QtCore/qtypeinfo.h \
		/opt/qt5.7.0/include/QtCore/qtypetraits.h \
		/opt/qt5.7.0/include/QtCore/qisenum.h \
		/opt/qt5.7.0/include/QtCore/qsysinfo.h \
		/opt/qt5.7.0/include/QtCore/qlogging.h \
		/opt/qt5.7.0/include/QtCore/qflags.h \
		/opt/qt5.7.0/include/QtCore/qatomic.h \
		/opt/qt5.7.0/include/QtCore/qbasicatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.7.0/include/QtCore/qgenericatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.7.0/include/QtCore/qatomic_msvc.h \
		/opt/qt5.7.0/include/QtCore/qglobalstatic.h \
		/opt/qt5.7.0/include/QtCore/qmutex.h \
		/opt/qt5.7.0/include/QtCore/qnumeric.h \
		/opt/qt5.7.0/include/QtCore/qversiontagging.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.7.0/include/QtCore/qstring.h \
		/opt/qt5.7.0/include/QtCore/qchar.h \
		/opt/qt5.7.0/include/QtCore/qbytearray.h \
		/opt/qt5.7.0/include/QtCore/qrefcount.h \
		/opt/qt5.7.0/include/QtCore/qarraydata.h \
		/opt/qt5.7.0/include/QtCore/qstringbuilder.h \
		/opt/qt5.7.0/include/QtCore/qlist.h \
		/opt/qt5.7.0/include/QtCore/qalgorithms.h \
		/opt/qt5.7.0/include/QtCore/qiterator.h \
		/opt/qt5.7.0/include/QtCore/qhashfunctions.h \
		/opt/qt5.7.0/include/QtCore/qpair.h \
		/opt/qt5.7.0/include/QtCore/qbytearraylist.h \
		/opt/qt5.7.0/include/QtCore/qstringlist.h \
		/opt/qt5.7.0/include/QtCore/qregexp.h \
		/opt/qt5.7.0/include/QtCore/qstringmatcher.h \
		/opt/qt5.7.0/include/QtCore/qcoreevent.h \
		/opt/qt5.7.0/include/QtCore/qscopedpointer.h \
		/opt/qt5.7.0/include/QtCore/qmetatype.h \
		/opt/qt5.7.0/include/QtCore/qvarlengtharray.h \
		/opt/qt5.7.0/include/QtCore/qcontainerfwd.h \
		/opt/qt5.7.0/include/QtCore/qobject_impl.h \
		/opt/qt5.7.0/include/QtCore/QDebug \
		/opt/qt5.7.0/include/QtCore/qdebug.h \
		/opt/qt5.7.0/include/QtCore/qhash.h \
		/opt/qt5.7.0/include/QtCore/qmap.h \
		/opt/qt5.7.0/include/QtCore/qtextstream.h \
		/opt/qt5.7.0/include/QtCore/qiodevice.h \
		/opt/qt5.7.0/include/QtCore/qlocale.h \
		/opt/qt5.7.0/include/QtCore/qvariant.h \
		/opt/qt5.7.0/include/QtCore/qshareddata.h \
		/opt/qt5.7.0/include/QtCore/qvector.h \
		/opt/qt5.7.0/include/QtCore/qpoint.h \
		/opt/qt5.7.0/include/QtCore/qset.h \
		/opt/qt5.7.0/include/QtCore/qcontiguouscache.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.7.0/include/QtCore/QSemaphore \
		/opt/qt5.7.0/include/QtCore/qsemaphore.h \
		/opt/qt5.7.0/include/QtCore/QMutex \
		/opt/qt5.7.0/include/QtCore/QMutexLocker \
		/opt/qt5.7.0/include/QtGui/QImage \
		/opt/qt5.7.0/include/QtGui/qimage.h \
		/opt/qt5.7.0/include/QtGui/qcolor.h \
		/opt/qt5.7.0/include/QtGui/qrgb.h \
		/opt/qt5.7.0/include/QtGui/qrgba64.h \
		/opt/qt5.7.0/include/QtGui/qpaintdevice.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.7.0/include/QtCore/qrect.h \
		/opt/qt5.7.0/include/QtCore/qmargins.h \
		/opt/qt5.7.0/include/QtCore/qsize.h \
		/opt/qt5.7.0/include/QtGui/qpixelformat.h \
		/opt/qt5.7.0/include/QtGui/qtransform.h \
		/opt/qt5.7.0/include/QtGui/qmatrix.h \
		/opt/qt5.7.0/include/QtGui/qpolygon.h \
		/opt/qt5.7.0/include/QtGui/qregion.h \
		/opt/qt5.7.0/include/QtCore/qdatastream.h \
		/opt/qt5.7.0/include/QtCore/qline.h \
		/opt/qt5.7.0/include/QtGui/qpainterpath.h \
		/opt/qt5.7.0/include/QtGui/QPixmap \
		/opt/qt5.7.0/include/QtGui/qpixmap.h \
		/opt/qt5.7.0/include/QtCore/QTime \
		/opt/qt5.7.0/include/QtCore/qdatetime.h \
		workerthread.h \
		/opt/qt5.7.0/bin/moc
	/opt/qt5.7.0/bin/moc $(DEFINES) -I/opt/qt5.7.0/mkspecs/linux-arm-gnueabi-g++ -I/home/jiangyu/code/qt/MiniPy -I/home/jiangyu/opencv/opencv-3.2.0/output/include -I/home/jiangyu/opencv/opencv-3.2.0/output/include/opencv -I/home/jiangyu/opencv/opencv-3.2.0/output/include/opencv2 -I/opt/qt5.7.0/include -I/opt/qt5.7.0/include/QtWidgets -I/opt/qt5.7.0/include/QtGui -I/opt/qt5.7.0/include/QtCore -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3 -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/arm-none-linux-gnueabi -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/backward -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include -I/usr/local/arm/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include-fixed -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include -I/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/libc/usr/include workerthread.h -o moc_workerthread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/opt/qt5.7.0/bin/uic
	/opt/qt5.7.0/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		/opt/qt5.7.0/include/QtWidgets/QWidget \
		/opt/qt5.7.0/include/QtWidgets/qwidget.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs.h \
		/opt/qt5.7.0/include/QtCore/qglobal.h \
		/opt/qt5.7.0/include/QtCore/qconfig.h \
		/opt/qt5.7.0/include/QtCore/qfeatures.h \
		/opt/qt5.7.0/include/QtCore/qsystemdetection.h \
		/opt/qt5.7.0/include/QtCore/qprocessordetection.h \
		/opt/qt5.7.0/include/QtCore/qcompilerdetection.h \
		/opt/qt5.7.0/include/QtCore/qtypeinfo.h \
		/opt/qt5.7.0/include/QtCore/qtypetraits.h \
		/opt/qt5.7.0/include/QtCore/qisenum.h \
		/opt/qt5.7.0/include/QtCore/qsysinfo.h \
		/opt/qt5.7.0/include/QtCore/qlogging.h \
		/opt/qt5.7.0/include/QtCore/qflags.h \
		/opt/qt5.7.0/include/QtCore/qatomic.h \
		/opt/qt5.7.0/include/QtCore/qbasicatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.7.0/include/QtCore/qgenericatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.7.0/include/QtCore/qatomic_msvc.h \
		/opt/qt5.7.0/include/QtCore/qglobalstatic.h \
		/opt/qt5.7.0/include/QtCore/qmutex.h \
		/opt/qt5.7.0/include/QtCore/qnumeric.h \
		/opt/qt5.7.0/include/QtCore/qversiontagging.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs.h \
		/opt/qt5.7.0/include/QtCore/qnamespace.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.7.0/include/QtCore/qobject.h \
		/opt/qt5.7.0/include/QtCore/qstring.h \
		/opt/qt5.7.0/include/QtCore/qchar.h \
		/opt/qt5.7.0/include/QtCore/qbytearray.h \
		/opt/qt5.7.0/include/QtCore/qrefcount.h \
		/opt/qt5.7.0/include/QtCore/qarraydata.h \
		/opt/qt5.7.0/include/QtCore/qstringbuilder.h \
		/opt/qt5.7.0/include/QtCore/qlist.h \
		/opt/qt5.7.0/include/QtCore/qalgorithms.h \
		/opt/qt5.7.0/include/QtCore/qiterator.h \
		/opt/qt5.7.0/include/QtCore/qhashfunctions.h \
		/opt/qt5.7.0/include/QtCore/qpair.h \
		/opt/qt5.7.0/include/QtCore/qbytearraylist.h \
		/opt/qt5.7.0/include/QtCore/qstringlist.h \
		/opt/qt5.7.0/include/QtCore/qregexp.h \
		/opt/qt5.7.0/include/QtCore/qstringmatcher.h \
		/opt/qt5.7.0/include/QtCore/qcoreevent.h \
		/opt/qt5.7.0/include/QtCore/qscopedpointer.h \
		/opt/qt5.7.0/include/QtCore/qmetatype.h \
		/opt/qt5.7.0/include/QtCore/qvarlengtharray.h \
		/opt/qt5.7.0/include/QtCore/qcontainerfwd.h \
		/opt/qt5.7.0/include/QtCore/qobject_impl.h \
		/opt/qt5.7.0/include/QtCore/qmargins.h \
		/opt/qt5.7.0/include/QtGui/qpaintdevice.h \
		/opt/qt5.7.0/include/QtCore/qrect.h \
		/opt/qt5.7.0/include/QtCore/qsize.h \
		/opt/qt5.7.0/include/QtCore/qpoint.h \
		/opt/qt5.7.0/include/QtGui/qpalette.h \
		/opt/qt5.7.0/include/QtGui/qcolor.h \
		/opt/qt5.7.0/include/QtGui/qrgb.h \
		/opt/qt5.7.0/include/QtGui/qrgba64.h \
		/opt/qt5.7.0/include/QtGui/qbrush.h \
		/opt/qt5.7.0/include/QtCore/qvector.h \
		/opt/qt5.7.0/include/QtGui/qmatrix.h \
		/opt/qt5.7.0/include/QtGui/qpolygon.h \
		/opt/qt5.7.0/include/QtGui/qregion.h \
		/opt/qt5.7.0/include/QtCore/qdatastream.h \
		/opt/qt5.7.0/include/QtCore/qiodevice.h \
		/opt/qt5.7.0/include/QtCore/qline.h \
		/opt/qt5.7.0/include/QtGui/qtransform.h \
		/opt/qt5.7.0/include/QtGui/qpainterpath.h \
		/opt/qt5.7.0/include/QtGui/qimage.h \
		/opt/qt5.7.0/include/QtGui/qpixelformat.h \
		/opt/qt5.7.0/include/QtGui/qpixmap.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer.h \
		/opt/qt5.7.0/include/QtCore/qshareddata.h \
		/opt/qt5.7.0/include/QtCore/qhash.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.7.0/include/QtGui/qfont.h \
		/opt/qt5.7.0/include/QtGui/qfontmetrics.h \
		/opt/qt5.7.0/include/QtGui/qfontinfo.h \
		/opt/qt5.7.0/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.7.0/include/QtGui/qcursor.h \
		/opt/qt5.7.0/include/QtGui/qkeysequence.h \
		/opt/qt5.7.0/include/QtGui/qevent.h \
		/opt/qt5.7.0/include/QtCore/qvariant.h \
		/opt/qt5.7.0/include/QtCore/qmap.h \
		/opt/qt5.7.0/include/QtCore/qdebug.h \
		/opt/qt5.7.0/include/QtCore/qtextstream.h \
		/opt/qt5.7.0/include/QtCore/qlocale.h \
		/opt/qt5.7.0/include/QtCore/qset.h \
		/opt/qt5.7.0/include/QtCore/qcontiguouscache.h \
		/opt/qt5.7.0/include/QtCore/qurl.h \
		/opt/qt5.7.0/include/QtCore/qurlquery.h \
		/opt/qt5.7.0/include/QtCore/qfile.h \
		/opt/qt5.7.0/include/QtCore/qfiledevice.h \
		/opt/qt5.7.0/include/QtGui/qvector2d.h \
		/opt/qt5.7.0/include/QtGui/qtouchdevice.h \
		/opt/qt5.7.0/include/QtWidgets/QMessageBox \
		/opt/qt5.7.0/include/QtWidgets/qmessagebox.h \
		/opt/qt5.7.0/include/QtWidgets/qdialog.h \
		/opt/qt5.7.0/include/QtGui/QImage \
		/opt/qt5.7.0/include/QtGui/QPixmap \
		/opt/qt5.7.0/include/QtCore/QTimer \
		/opt/qt5.7.0/include/QtCore/qtimer.h \
		/opt/qt5.7.0/include/QtCore/qbasictimer.h \
		/opt/qt5.7.0/include/QtCore/QTime \
		/opt/qt5.7.0/include/QtCore/qdatetime.h \
		/opt/qt5.7.0/include/QtCore/QDebug \
		/opt/qt5.7.0/include/QtGui/QPainter \
		/opt/qt5.7.0/include/QtGui/qpainter.h \
		/opt/qt5.7.0/include/QtGui/qtextoption.h \
		/opt/qt5.7.0/include/QtGui/qpen.h \
		/opt/qt5.7.0/include/QtCore/QThread \
		/opt/qt5.7.0/include/QtCore/qthread.h \
		/opt/qt5.7.0/include/QtGui/QCloseEvent \
		/opt/qt5.7.0/include/QtCore/QMutex \
		/opt/qt5.7.0/include/QtCore/QMutexLocker \
		v4l2Cap.h \
		workerthread.h \
		/opt/qt5.7.0/include/QtCore/QObject \
		/opt/qt5.7.0/include/QtCore/QSemaphore \
		/opt/qt5.7.0/include/QtCore/qsemaphore.h \
		opencv_measure.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv_modules.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvdef.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/hal/interface.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/version.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ptr.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/neon_utils.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/traits.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/matx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/saturate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/fast_math.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/bufferpool.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/persistence.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/operations.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/utility.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/core_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/optim.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ovx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/features2d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/miniflann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/defines.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/config.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/affine.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d/calib3d_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/flann_base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/general.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/matrix.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/params.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/any.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/saving.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/nn_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/result_set.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/all_indices.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dynamic_bitset.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dist.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/heap.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/allocator.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/random.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_single_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kmeans_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/logger.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/composite_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/linear_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_table.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/autotuned_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/ground_truth.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/index_testing.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/timer.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/sampling.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui/highgui_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/imgproc_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio/videoio_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/ml.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/objdetect_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo/photo_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/emdL1.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_transformer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/hist_cost.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_distance.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda_types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/matchers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/camera.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/blenders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/background_segm.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/stabilizer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/global_motion.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/outlier_rejection.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/frame_source.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/log.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/inpainting.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/deblurring.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/wobble_suppression.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/ring_buffer.hpp \
		/opt/qt5.7.0/include/QtWidgets/QApplication \
		/opt/qt5.7.0/include/QtWidgets/qapplication.h \
		/opt/qt5.7.0/include/QtCore/qcoreapplication.h \
		/opt/qt5.7.0/include/QtCore/qeventloop.h \
		/opt/qt5.7.0/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.7.0/include/QtGui/qguiapplication.h \
		/opt/qt5.7.0/include/QtGui/qinputmethod.h \
		/opt/qt5.7.0/include/QtCore/QTextCodec \
		/opt/qt5.7.0/include/QtCore/qtextcodec.h \
		/opt/qt5.7.0/include/QtGui/QFontDatabase \
		/opt/qt5.7.0/include/QtGui/qfontdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		/opt/qt5.7.0/include/QtWidgets/QWidget \
		/opt/qt5.7.0/include/QtWidgets/qwidget.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs.h \
		/opt/qt5.7.0/include/QtCore/qglobal.h \
		/opt/qt5.7.0/include/QtCore/qconfig.h \
		/opt/qt5.7.0/include/QtCore/qfeatures.h \
		/opt/qt5.7.0/include/QtCore/qsystemdetection.h \
		/opt/qt5.7.0/include/QtCore/qprocessordetection.h \
		/opt/qt5.7.0/include/QtCore/qcompilerdetection.h \
		/opt/qt5.7.0/include/QtCore/qtypeinfo.h \
		/opt/qt5.7.0/include/QtCore/qtypetraits.h \
		/opt/qt5.7.0/include/QtCore/qisenum.h \
		/opt/qt5.7.0/include/QtCore/qsysinfo.h \
		/opt/qt5.7.0/include/QtCore/qlogging.h \
		/opt/qt5.7.0/include/QtCore/qflags.h \
		/opt/qt5.7.0/include/QtCore/qatomic.h \
		/opt/qt5.7.0/include/QtCore/qbasicatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.7.0/include/QtCore/qgenericatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.7.0/include/QtCore/qatomic_msvc.h \
		/opt/qt5.7.0/include/QtCore/qglobalstatic.h \
		/opt/qt5.7.0/include/QtCore/qmutex.h \
		/opt/qt5.7.0/include/QtCore/qnumeric.h \
		/opt/qt5.7.0/include/QtCore/qversiontagging.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs.h \
		/opt/qt5.7.0/include/QtCore/qnamespace.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.7.0/include/QtCore/qobject.h \
		/opt/qt5.7.0/include/QtCore/qstring.h \
		/opt/qt5.7.0/include/QtCore/qchar.h \
		/opt/qt5.7.0/include/QtCore/qbytearray.h \
		/opt/qt5.7.0/include/QtCore/qrefcount.h \
		/opt/qt5.7.0/include/QtCore/qarraydata.h \
		/opt/qt5.7.0/include/QtCore/qstringbuilder.h \
		/opt/qt5.7.0/include/QtCore/qlist.h \
		/opt/qt5.7.0/include/QtCore/qalgorithms.h \
		/opt/qt5.7.0/include/QtCore/qiterator.h \
		/opt/qt5.7.0/include/QtCore/qhashfunctions.h \
		/opt/qt5.7.0/include/QtCore/qpair.h \
		/opt/qt5.7.0/include/QtCore/qbytearraylist.h \
		/opt/qt5.7.0/include/QtCore/qstringlist.h \
		/opt/qt5.7.0/include/QtCore/qregexp.h \
		/opt/qt5.7.0/include/QtCore/qstringmatcher.h \
		/opt/qt5.7.0/include/QtCore/qcoreevent.h \
		/opt/qt5.7.0/include/QtCore/qscopedpointer.h \
		/opt/qt5.7.0/include/QtCore/qmetatype.h \
		/opt/qt5.7.0/include/QtCore/qvarlengtharray.h \
		/opt/qt5.7.0/include/QtCore/qcontainerfwd.h \
		/opt/qt5.7.0/include/QtCore/qobject_impl.h \
		/opt/qt5.7.0/include/QtCore/qmargins.h \
		/opt/qt5.7.0/include/QtGui/qpaintdevice.h \
		/opt/qt5.7.0/include/QtCore/qrect.h \
		/opt/qt5.7.0/include/QtCore/qsize.h \
		/opt/qt5.7.0/include/QtCore/qpoint.h \
		/opt/qt5.7.0/include/QtGui/qpalette.h \
		/opt/qt5.7.0/include/QtGui/qcolor.h \
		/opt/qt5.7.0/include/QtGui/qrgb.h \
		/opt/qt5.7.0/include/QtGui/qrgba64.h \
		/opt/qt5.7.0/include/QtGui/qbrush.h \
		/opt/qt5.7.0/include/QtCore/qvector.h \
		/opt/qt5.7.0/include/QtGui/qmatrix.h \
		/opt/qt5.7.0/include/QtGui/qpolygon.h \
		/opt/qt5.7.0/include/QtGui/qregion.h \
		/opt/qt5.7.0/include/QtCore/qdatastream.h \
		/opt/qt5.7.0/include/QtCore/qiodevice.h \
		/opt/qt5.7.0/include/QtCore/qline.h \
		/opt/qt5.7.0/include/QtGui/qtransform.h \
		/opt/qt5.7.0/include/QtGui/qpainterpath.h \
		/opt/qt5.7.0/include/QtGui/qimage.h \
		/opt/qt5.7.0/include/QtGui/qpixelformat.h \
		/opt/qt5.7.0/include/QtGui/qpixmap.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer.h \
		/opt/qt5.7.0/include/QtCore/qshareddata.h \
		/opt/qt5.7.0/include/QtCore/qhash.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.7.0/include/QtGui/qfont.h \
		/opt/qt5.7.0/include/QtGui/qfontmetrics.h \
		/opt/qt5.7.0/include/QtGui/qfontinfo.h \
		/opt/qt5.7.0/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.7.0/include/QtGui/qcursor.h \
		/opt/qt5.7.0/include/QtGui/qkeysequence.h \
		/opt/qt5.7.0/include/QtGui/qevent.h \
		/opt/qt5.7.0/include/QtCore/qvariant.h \
		/opt/qt5.7.0/include/QtCore/qmap.h \
		/opt/qt5.7.0/include/QtCore/qdebug.h \
		/opt/qt5.7.0/include/QtCore/qtextstream.h \
		/opt/qt5.7.0/include/QtCore/qlocale.h \
		/opt/qt5.7.0/include/QtCore/qset.h \
		/opt/qt5.7.0/include/QtCore/qcontiguouscache.h \
		/opt/qt5.7.0/include/QtCore/qurl.h \
		/opt/qt5.7.0/include/QtCore/qurlquery.h \
		/opt/qt5.7.0/include/QtCore/qfile.h \
		/opt/qt5.7.0/include/QtCore/qfiledevice.h \
		/opt/qt5.7.0/include/QtGui/qvector2d.h \
		/opt/qt5.7.0/include/QtGui/qtouchdevice.h \
		/opt/qt5.7.0/include/QtWidgets/QMessageBox \
		/opt/qt5.7.0/include/QtWidgets/qmessagebox.h \
		/opt/qt5.7.0/include/QtWidgets/qdialog.h \
		/opt/qt5.7.0/include/QtGui/QImage \
		/opt/qt5.7.0/include/QtGui/QPixmap \
		/opt/qt5.7.0/include/QtCore/QTimer \
		/opt/qt5.7.0/include/QtCore/qtimer.h \
		/opt/qt5.7.0/include/QtCore/qbasictimer.h \
		/opt/qt5.7.0/include/QtCore/QTime \
		/opt/qt5.7.0/include/QtCore/qdatetime.h \
		/opt/qt5.7.0/include/QtCore/QDebug \
		/opt/qt5.7.0/include/QtGui/QPainter \
		/opt/qt5.7.0/include/QtGui/qpainter.h \
		/opt/qt5.7.0/include/QtGui/qtextoption.h \
		/opt/qt5.7.0/include/QtGui/qpen.h \
		/opt/qt5.7.0/include/QtCore/QThread \
		/opt/qt5.7.0/include/QtCore/qthread.h \
		/opt/qt5.7.0/include/QtGui/QCloseEvent \
		/opt/qt5.7.0/include/QtCore/QMutex \
		/opt/qt5.7.0/include/QtCore/QMutexLocker \
		v4l2Cap.h \
		workerthread.h \
		/opt/qt5.7.0/include/QtCore/QObject \
		/opt/qt5.7.0/include/QtCore/QSemaphore \
		/opt/qt5.7.0/include/QtCore/qsemaphore.h \
		opencv_measure.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv_modules.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvdef.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/hal/interface.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/version.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ptr.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/neon_utils.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/traits.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/matx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/saturate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/fast_math.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/bufferpool.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/persistence.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/operations.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/utility.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/core_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/optim.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ovx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/features2d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/miniflann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/defines.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/config.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/affine.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d/calib3d_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/flann_base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/general.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/matrix.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/params.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/any.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/saving.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/nn_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/result_set.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/all_indices.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dynamic_bitset.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dist.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/heap.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/allocator.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/random.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_single_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kmeans_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/logger.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/composite_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/linear_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_table.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/autotuned_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/ground_truth.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/index_testing.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/timer.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/sampling.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui/highgui_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/imgproc_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio/videoio_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/ml.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/objdetect_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo/photo_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/emdL1.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_transformer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/hist_cost.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_distance.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda_types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/matchers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/camera.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/blenders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/background_segm.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/stabilizer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/global_motion.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/outlier_rejection.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/frame_source.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/log.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/inpainting.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/deblurring.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/wobble_suppression.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/ring_buffer.hpp \
		ui_widget.h \
		/opt/qt5.7.0/include/QtCore/QVariant \
		/opt/qt5.7.0/include/QtWidgets/QAction \
		/opt/qt5.7.0/include/QtWidgets/qaction.h \
		/opt/qt5.7.0/include/QtGui/qicon.h \
		/opt/qt5.7.0/include/QtWidgets/qactiongroup.h \
		/opt/qt5.7.0/include/QtWidgets/QApplication \
		/opt/qt5.7.0/include/QtWidgets/qapplication.h \
		/opt/qt5.7.0/include/QtCore/qcoreapplication.h \
		/opt/qt5.7.0/include/QtCore/qeventloop.h \
		/opt/qt5.7.0/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.7.0/include/QtGui/qguiapplication.h \
		/opt/qt5.7.0/include/QtGui/qinputmethod.h \
		/opt/qt5.7.0/include/QtWidgets/QButtonGroup \
		/opt/qt5.7.0/include/QtWidgets/qbuttongroup.h \
		/opt/qt5.7.0/include/QtWidgets/QDial \
		/opt/qt5.7.0/include/QtWidgets/qdial.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractslider.h \
		/opt/qt5.7.0/include/QtWidgets/QFrame \
		/opt/qt5.7.0/include/QtWidgets/qframe.h \
		/opt/qt5.7.0/include/QtWidgets/QHeaderView \
		/opt/qt5.7.0/include/QtWidgets/qheaderview.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractitemview.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.7.0/include/QtCore/qabstractitemmodel.h \
		/opt/qt5.7.0/include/QtCore/qitemselectionmodel.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt5.7.0/include/QtWidgets/qstyleoption.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractspinbox.h \
		/opt/qt5.7.0/include/QtGui/qvalidator.h \
		/opt/qt5.7.0/include/QtCore/qregularexpression.h \
		/opt/qt5.7.0/include/QtWidgets/qslider.h \
		/opt/qt5.7.0/include/QtWidgets/qstyle.h \
		/opt/qt5.7.0/include/QtWidgets/qtabbar.h \
		/opt/qt5.7.0/include/QtWidgets/qtabwidget.h \
		/opt/qt5.7.0/include/QtWidgets/qrubberband.h \
		/opt/qt5.7.0/include/QtWidgets/QLineEdit \
		/opt/qt5.7.0/include/QtWidgets/qlineedit.h \
		/opt/qt5.7.0/include/QtGui/qtextcursor.h \
		/opt/qt5.7.0/include/QtGui/qtextformat.h \
		/opt/qt5.7.0/include/QtWidgets/QPushButton \
		/opt/qt5.7.0/include/QtWidgets/qpushbutton.h \
		/opt/qt5.7.0/include/QtWidgets/qabstractbutton.h \
		/opt/qt5.7.0/include/QtWidgets/QSlider
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

v4l2Cap.o: v4l2Cap.c v4l2Cap.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o v4l2Cap.o v4l2Cap.c

workerthread.o: workerthread.cpp workerthread.h \
		/opt/qt5.7.0/include/QtCore/QObject \
		/opt/qt5.7.0/include/QtCore/qobject.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs.h \
		/opt/qt5.7.0/include/QtCore/qnamespace.h \
		/opt/qt5.7.0/include/QtCore/qglobal.h \
		/opt/qt5.7.0/include/QtCore/qconfig.h \
		/opt/qt5.7.0/include/QtCore/qfeatures.h \
		/opt/qt5.7.0/include/QtCore/qsystemdetection.h \
		/opt/qt5.7.0/include/QtCore/qprocessordetection.h \
		/opt/qt5.7.0/include/QtCore/qcompilerdetection.h \
		/opt/qt5.7.0/include/QtCore/qtypeinfo.h \
		/opt/qt5.7.0/include/QtCore/qtypetraits.h \
		/opt/qt5.7.0/include/QtCore/qisenum.h \
		/opt/qt5.7.0/include/QtCore/qsysinfo.h \
		/opt/qt5.7.0/include/QtCore/qlogging.h \
		/opt/qt5.7.0/include/QtCore/qflags.h \
		/opt/qt5.7.0/include/QtCore/qatomic.h \
		/opt/qt5.7.0/include/QtCore/qbasicatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.7.0/include/QtCore/qgenericatomic.h \
		/opt/qt5.7.0/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.7.0/include/QtCore/qatomic_msvc.h \
		/opt/qt5.7.0/include/QtCore/qglobalstatic.h \
		/opt/qt5.7.0/include/QtCore/qmutex.h \
		/opt/qt5.7.0/include/QtCore/qnumeric.h \
		/opt/qt5.7.0/include/QtCore/qversiontagging.h \
		/opt/qt5.7.0/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.7.0/include/QtCore/qstring.h \
		/opt/qt5.7.0/include/QtCore/qchar.h \
		/opt/qt5.7.0/include/QtCore/qbytearray.h \
		/opt/qt5.7.0/include/QtCore/qrefcount.h \
		/opt/qt5.7.0/include/QtCore/qarraydata.h \
		/opt/qt5.7.0/include/QtCore/qstringbuilder.h \
		/opt/qt5.7.0/include/QtCore/qlist.h \
		/opt/qt5.7.0/include/QtCore/qalgorithms.h \
		/opt/qt5.7.0/include/QtCore/qiterator.h \
		/opt/qt5.7.0/include/QtCore/qhashfunctions.h \
		/opt/qt5.7.0/include/QtCore/qpair.h \
		/opt/qt5.7.0/include/QtCore/qbytearraylist.h \
		/opt/qt5.7.0/include/QtCore/qstringlist.h \
		/opt/qt5.7.0/include/QtCore/qregexp.h \
		/opt/qt5.7.0/include/QtCore/qstringmatcher.h \
		/opt/qt5.7.0/include/QtCore/qcoreevent.h \
		/opt/qt5.7.0/include/QtCore/qscopedpointer.h \
		/opt/qt5.7.0/include/QtCore/qmetatype.h \
		/opt/qt5.7.0/include/QtCore/qvarlengtharray.h \
		/opt/qt5.7.0/include/QtCore/qcontainerfwd.h \
		/opt/qt5.7.0/include/QtCore/qobject_impl.h \
		/opt/qt5.7.0/include/QtCore/QDebug \
		/opt/qt5.7.0/include/QtCore/qdebug.h \
		/opt/qt5.7.0/include/QtCore/qhash.h \
		/opt/qt5.7.0/include/QtCore/qmap.h \
		/opt/qt5.7.0/include/QtCore/qtextstream.h \
		/opt/qt5.7.0/include/QtCore/qiodevice.h \
		/opt/qt5.7.0/include/QtCore/qlocale.h \
		/opt/qt5.7.0/include/QtCore/qvariant.h \
		/opt/qt5.7.0/include/QtCore/qshareddata.h \
		/opt/qt5.7.0/include/QtCore/qvector.h \
		/opt/qt5.7.0/include/QtCore/qpoint.h \
		/opt/qt5.7.0/include/QtCore/qset.h \
		/opt/qt5.7.0/include/QtCore/qcontiguouscache.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer.h \
		/opt/qt5.7.0/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.7.0/include/QtCore/QSemaphore \
		/opt/qt5.7.0/include/QtCore/qsemaphore.h \
		/opt/qt5.7.0/include/QtCore/QMutex \
		/opt/qt5.7.0/include/QtCore/QMutexLocker \
		/opt/qt5.7.0/include/QtGui/QImage \
		/opt/qt5.7.0/include/QtGui/qimage.h \
		/opt/qt5.7.0/include/QtGui/qcolor.h \
		/opt/qt5.7.0/include/QtGui/qrgb.h \
		/opt/qt5.7.0/include/QtGui/qrgba64.h \
		/opt/qt5.7.0/include/QtGui/qpaintdevice.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs.h \
		/opt/qt5.7.0/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.7.0/include/QtCore/qrect.h \
		/opt/qt5.7.0/include/QtCore/qmargins.h \
		/opt/qt5.7.0/include/QtCore/qsize.h \
		/opt/qt5.7.0/include/QtGui/qpixelformat.h \
		/opt/qt5.7.0/include/QtGui/qtransform.h \
		/opt/qt5.7.0/include/QtGui/qmatrix.h \
		/opt/qt5.7.0/include/QtGui/qpolygon.h \
		/opt/qt5.7.0/include/QtGui/qregion.h \
		/opt/qt5.7.0/include/QtCore/qdatastream.h \
		/opt/qt5.7.0/include/QtCore/qline.h \
		/opt/qt5.7.0/include/QtGui/qpainterpath.h \
		/opt/qt5.7.0/include/QtGui/QPixmap \
		/opt/qt5.7.0/include/QtGui/qpixmap.h \
		/opt/qt5.7.0/include/QtCore/QTime \
		/opt/qt5.7.0/include/QtCore/qdatetime.h \
		v4l2Cap.h \
		exifparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workerthread.o workerthread.cpp

opencv_measure.o: opencv_measure.cpp opencv_measure.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/opencv_modules.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvdef.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/hal/interface.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/version.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ptr.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/neon_utils.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/traits.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/matx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/saturate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/fast_math.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/bufferpool.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/mat.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/persistence.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/operations.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cvstd.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/utility.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/core_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/optim.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/ovx.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/features2d.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/miniflann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/defines.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/config.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/affine.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/calib3d/calib3d_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/flann_base.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/general.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/matrix.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/params.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/any.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/saving.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/nn_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/result_set.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/all_indices.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dynamic_bitset.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/dist.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/heap.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/allocator.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/random.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kdtree_single_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/kmeans_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/logger.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/composite_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/linear_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/lsh_table.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/autotuned_index.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/ground_truth.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/index_testing.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/timer.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/flann/sampling.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/highgui/highgui_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/imgproc_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc/types_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videoio/videoio_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/imgproc.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/ml.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/objdetect/objdetect_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/photo/photo_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/emdL1.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_transformer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/hist_cost.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/shape/shape_distance.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda_types.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/core/cuda.inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/matchers.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/util_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/camera.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/stitching/detail/blenders.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/superres/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/background_segm.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/video/tracking_c.h \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/stabilizer.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/global_motion.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/optical_flow.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_core.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/outlier_rejection.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/frame_source.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/log.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/inpainting.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/deblurring.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/wobble_suppression.hpp \
		../../../opencv/opencv-3.2.0/output/include/opencv2/videostab/ring_buffer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o opencv_measure.o opencv_measure.cpp

makeexif.o: makeexif.c exifparam.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o makeexif.o makeexif.c

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_workerthread.o: moc_workerthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_workerthread.o moc_workerthread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

